In [46]:
import numpy as np

def diagDom(x):
    
    x = np.array(x)
    diag = np.diag(x)

    oD = np.sum(np.abs(x), axis=1) - diag

    if np.all(diag > oD):
        return True
    else :
        return False

In [47]:
def gauss_seidel(x, y, epsilon = 0.01, t = 15):
    if not diagDom(x):
        print('is not diagonally dominant')
        return
    
    x = np.array(x)
    y = np.array(y)
    diag = np.diag(np.abs(x))

    
    x = -x
    np.fill_diagonal(x, 0)

    mtx_old = np.zeros(x[0].shape)

   
    for i in range(t):
        mtx_new = np.array(mtx_old)
        for idx, row in enumerate(x):
            mtx_new[idx] = (y[idx] + np.dot(row, mtx_new)) / diag[idx]

        print(f'iterasi ke - {i}')
        print(mtx_new)

        dx = np.sqrt(np.dot(mtx_new - mtx_old, mtx_new - mtx_old))
        print(f'dx : -{dx}')

        if dx < epsilon:
            print('converged')
            return
        
        mtx_old = mtx_new

    print('not converged')
    return

In [48]:
matrix_x = [[10, 4, 5],
            [1, 6, 1],
            [3, 1, 6]]
matrix_y = [8, 5 ,10]

gauss_seidel(matrix_x, matrix_y)

iterasi ke - 0
[0.8  0.7  1.15]
dx : -1.5660459763365826
iterasi ke - 1
[-0.055       0.65083333  1.58569444]
dx : -0.9608704439365717
iterasi ke - 2
[-0.25318056  0.61124769  1.69138233]
dx : -0.22806245930668492
iterasi ke - 3
[-0.29019024  0.59980132  1.7117949 ]
dx : -0.04378822902864041
iterasi ke - 4
[-0.29581798  0.59733718  1.71501946]
dx : -0.006938385517329205
converged
