In [2]:
import numpy as np

def isDiagonallyDominant(x):

    x = np.array(x)
    
    diag = np.diag(np.abs(x)) #np.abs(x)

    off_diag = np.sum(np.abs(x), axis = 1) - diag

    if np.all(diag > off_diag):
        return True
    else:
        return False
    
def gauss_seidel(x, y, epsilon = 0.01, t = 15):
    x = np.array(x)
    y = np.array(y)

    if not isDiagonallyDominant(x):
        print ("Is not diagonally dominant")
        return 

    diag = np.diag(x)

    x_off_diag = x - np.diagflat(diag) #new

    sol = np.zeros_like(y) #new

    for i in range(t):
        sol_new = np.copy(sol) #new

        for idx in range(len(x)):
            sol_new[idx] = (y[idx] - np.dot(x_off_diag[idx], sol_new)) / diag[idx] #new

        dx = np.linalg.norm(sol_new - sol) #new

        print(f'iterasi-{i}')
        print(sol_new)

        print (f'dx : {dx})')

        if dx < epsilon:
            print('Complated')
            return sol_new
        
        sol = sol_new

    print('not complated')
    return

matrixx = [[10,4,5],
            [1,6,1],
            [3,1,6]]

matrixy = [8,5,10]

isDiagonallyDominant(matrixx)

gauss_seidel(matrixx,matrixy)

iterasi-0
[0 0 1]
dx : 1.0)
iterasi-1
[0 0 1]
dx : 0.0)
Complated


array([0, 0, 1])